export const TYPES = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  SET_TOTAL: "SET_TOTAL",
  CLEAR: "CLEAR",
};
